title: Life is good to live
theme: minima
author: GitHub BruttieJP
email: your-email@domain.com
description: > #I really hate doing this but it’s a good thing to always learn something new.




show_excerpts: true # set to false to remove excerpts on the homepage
